version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kafka-chat-2:1:1"
    depends_on:
      - zookeeper

  kafka-consumer:
    image: wurstmeister/kafka
    container_name: kafka-consumer
    command: kafka-console-consumer --bootstrap-server kafka:9092 --topic kafka-chat-2 --from-beginning
    depends_on:
      - kafka
